services:
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ally-ollama
  #   ports:
  #     - "11434:11434"
  #   environment:
  #     OLLAMA_HOST: 0.0.0.0:11434
  #   volumes:
  #     - ollama_data:/root/.ollama


  api-server:
    build: ./api
    container_name: ally-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      OLLAMA_URL: ${OLLAMA_URL}
      API_KEY: ${API_KEY}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      MAX_CONTEXT_LEN: ${MAX_CONTEXT_LEN}
      OLLAMA_CF_ACCESS_CLIENT_ID: ${OLLAMA_CF_ACCESS_CLIENT_ID}
      OLLAMA_CF_ACCESS_CLIENT_SECRET: ${OLLAMA_CF_ACCESS_CLIENT_SECRET}
      HF_TOKEN: ${HF_TOKEN:-}
      HF_HOME: /root/.cache/huggingface
      TORCH_HOME: /root/.cache/torch
    volumes:
      - ./api:/app
      - whisperx_models:/root/.cache/huggingface
      - torch_models:/root/.cache/torch
    # depends_on:
    #   - ollama

volumes:
  # ollama_data:
  whisperx_models:
  torch_models: